//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int CategoryId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Currency { get; set; }
        public Nullable<int> Units { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
